// Autogenerated Pigeon file for QRCodeApi and BiometricsApi
// Save this as qrcode_biometrics_api.dart

import 'package:pigeon/pigeon.dart';

class QRCode {
  String? rawValue;
  int? timestamp;
}

@HostApi()
abstract class QRCodeApi {
  // Method to scan a QR code
  String? scanQRCode();

  // Method to retrieve all saved QR codes
  @async
  List<QRCode?> getAllSavedQRCodes();
}

@HostApi()
abstract class BiometricAuthApi {
  bool isBiometricAvailable();
  bool authenticate(String promptMessage);
}
