name: Run Android Native Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  android-native-tests:
    name: Run Android Native Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build and run Android native tests
      - name: Run Android Native Tests
        working-directory: android
        run: ./gradlew testDebugUnitTest

      # Step 5: Generate Android Lint Report (Optional)
      - name: Run Android Lint
        working-directory: android
        run: ./gradlew lintDebug
