name: Run Flutter and Android Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  flutter-tests:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # Explicit Flutter version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Run Flutter tests
      - name: Run Flutter Tests
        run: flutter test


  android-native-tests:
    name: Run Android Native Tests
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Use Java 17 to match Gradle compatibility)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Install Flutter SDK
      - name: Install Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git C:\flutter
          echo "flutterSdkPath=C:\flutter" >> $GITHUB_ENV
          C:\flutter\bin\flutter doctor

      # Step 4: Clean Flutter build cache
      - name: Flutter Clean
        run: C:\flutter\bin\flutter clean

      # Step 5: Resolve Flutter dependencies
      - name: Flutter Pub Get
        run: C:\flutter\bin\flutter pub get

      # Step 6: Cache Gradle dependencies (Path adjusted for Windows)
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\.gradle\caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 7: Grant execute permissions for Gradle Wrapper (Optional on Windows)
      - name: Ensure Gradlew Permissions
        run: icacls android\gradlew /grant Everyone:F

      # Step 8: Debug setup (Optional but helpful)
      - name: Verify Environment
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          C:\flutter\bin\flutter doctor
          android\gradlew --version

      # Step 9: Run Android native tests
      - name: Run Android Native Tests
        working-directory: android
        run: android\gradlew testDebugUnitTest --stacktrace --info

      # Step 10: Run Android Lint (Optional)
      - name: Run Android Lint
        working-directory: android
        run: android\gradlew lintDebug
