name: Run Flutter and Android Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  flutter-tests:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # Explicit Flutter version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Run Flutter tests
      - name: Run Flutter Tests
        run: flutter test


  android-native-tests:
    name: Run Android Native Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Ensure Java 17 for compatibility)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Install Flutter SDK
      - name: Install Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git /opt/flutter
          echo "flutterSdkPath=/opt/flutter" >> $GITHUB_ENV
          /opt/flutter/bin/flutter doctor

      # Step 4: Clean Flutter build cache
      - name: Flutter Clean
        run: /opt/flutter/bin/flutter clean

      # Step 5: Resolve Flutter dependencies
      - name: Flutter Pub Get
        run: /opt/flutter/bin/flutter pub get

      # Step 6: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 7: Grant execute permissions for Gradle Wrapper
      - name: Grant execute permissions for Gradle Wrapper
        run: chmod +x ./android/gradlew

      # Step 8: Debug setup (Optional)
      - name: Verify Environment
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          /opt/flutter/bin/flutter doctor
          ./android/gradlew --version

      # Step 9: Build and run Android native tests
      - name: Run Android Native Tests
        working-directory: android
        run: ./gradlew testDebugUnitTest

      # Step 10: Run Android Lint (Optional)
      - name: Run Android Lint
        working-directory: android
        run: ./gradlew lintDebug
