name: Run Flutter and Android Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  flutter-tests:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # Explicit Flutter version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Run Flutter tests
      - name: Run Flutter Tests
        run: flutter test


  android-native-tests:
    name: Run Android Native Tests
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Install Flutter SDK
      - name: Install Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git C:\flutter
          echo "flutterSdkPath=C:\flutter" >> $GITHUB_ENV
          C:\flutter\bin\flutter doctor

      # Step 4: Clean Flutter build cache
      - name: Flutter Clean
        run: C:\flutter\bin\flutter clean

      # Step 5: Resolve Flutter dependencies
      - name: Flutter Pub Get
        run: C:\flutter\bin\flutter pub get

      # Step 6: Debug Android Directory
      - name: Debug Android Directory
        run: dir android

      # Step 7: Run Android native tests
      - name: Run Android Native Tests
        working-directory: android
        run: cmd /c gradlew.bat testDebugUnitTest --stacktrace --info

      # Step 8: Run Android Lint (Optional)
      - name: Run Android Lint
        working-directory: android
        run: cmd /c gradlew.bat lintDebug
